---
language: go
go:
- 1.16.x
- tip
- 1.15.x
- 1.14.x
- 1.13.x
#- 1.12.x
sudo: false

go_import_path: github.com/dolmen-go/sqlfunc

before_install:
- go get -t -v ./...

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
