sonar.organization=dolmen-go
sonar.projectKey=dolmen-go_sqlfunc

sonar.go.activate=true
sonar.dre.go.activate=true

# Output of "go test -json"
# sonar.go.tests.reportPaths=

# https://docs.sonarsource.com/sonarqube-server/analyzing-source-code/test-coverage/go-test-coverage
sonar.go.coverage.reportPaths=coverage.out

# sonar.go.golangci-lint.reportPaths=

# TODO
# sonar.githubactions.actionlint.reportPaths

# https://sonarcloud.io/project/settings?category=exclusions&id=dolmen-go_sqlfunc

# Ignore duplications in unit test code
sonar.cpd.exclusions=*_test.go


# TODO ignore go:S100, go:S1192 in *_test.go
# TODO ignore go:S3776 // Refactor this method to reduce its Cognitive Complexity...
