sonar.organization=dolmen-go
sonar.projectKey=dolmen-go_sqlfunc

sonar.go.activate=true
sonar.dre.go.activate=true

# Output of "go test -json"
# sonar.go.tests.reportPaths=

# https://docs.sonarsource.com/sonarqube-server/analyzing-source-code/test-coverage/go-test-coverage
sonar.go.coverage.reportPaths=coverage.out

# sonar.go.golangci-lint.reportPaths=

# TODO
# sonar.githubactions.actionlint.reportPaths
