//go:build sqlfunc_registry_on || !sqlfunc_registry_off

// Code generated by sqlfunc-gen; DO NOT EDIT.

package sqlfunc_test

import "github.com/dolmen-go/sqlfunc/sqlfuncregistry"

import (
	"context"
	sql "database/sql"
	"github.com/dolmen-go/sqlfunc"
)

func init() {
	sqlfuncregistry.Exec[func(context.Context, *sql.Tx, float64, float64, string) (sql.Result, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, *sql.Tx, float64, float64, string) (sql.Result, error))) = func(ctx context.Context, tx *sql.Tx, in0 float64, in1 float64, in2 string) (sql.Result, error) {
				stmtTx := stmt
				if tx != nil {
					stmtTx = tx.StmtContext(ctx, stmt)
					defer stmtTx.Close()
				}
				return stmtTx.ExecContext(ctx, in0, in1, in2)
			}
		},
	)

	sqlfuncregistry.Exec[func(context.Context, float32, float32, string) error](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, float32, float32, string) error)) = func(ctx context.Context, in0 float32, in1 float32, in2 string) (err error) {
				_, err = stmt.ExecContext(ctx, in0, in1, in2)
				return
			}
		},
	)

	sqlfuncregistry.Exec[func(context.Context, string) (sql.Result, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (sql.Result, error))) = func(ctx context.Context, in0 string) (sql.Result, error) {
				return stmt.ExecContext(ctx, in0)
			}
		},
	)

	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(*int64) error) error {
		var (
			v0 *int64
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		return cb(v0)
	})

	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(sql.Null[int64]) error) error {
		var (
			v0 sql.Null[int64]
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		return cb(v0)
	})

	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(float64, float64)) error {
		var (
			v0 float64
			v1 float64
		)
		if err := rows.Scan(&v0, &v1); err != nil {
			return err
		}
		cb(v0, v1)
		return nil
	})

	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(int)) error {
		var (
			v0 int
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		cb(v0)
		return nil
	})

	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(int) bool) error {
		var (
			v0 int
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		if !cb(v0) {
			return sqlfunc.Break
		}
		return nil
	})

	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(int) error) error {
		var (
			v0 int
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		return cb(v0)
	})

	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(string)) error {
		var (
			v0 string
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		cb(v0)
		return nil
	})

	sqlfuncregistry.Query[func(context.Context) (*sql.Rows, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context) (*sql.Rows, error))) = func(ctx context.Context) (*sql.Rows, error) {
				return stmt.QueryContext(ctx)
			}
		},
	)

	sqlfuncregistry.Query[func(context.Context, *sql.Tx, string) (*sql.Rows, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, *sql.Tx, string) (*sql.Rows, error))) = func(ctx context.Context, tx *sql.Tx, in0 string) (*sql.Rows, error) {
				stmtTx := stmt
				if tx != nil {
					stmtTx = tx.StmtContext(ctx, stmt)
					defer stmtTx.Close()
				}
				return stmtTx.QueryContext(ctx, in0)
			}
		},
	)

	sqlfuncregistry.QueryRow[func(context.Context) (int64, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context) (int64, error))) = func(ctx context.Context) (out0 int64, err error) {
				err = stmt.QueryRowContext(ctx).Scan(&out0)
				return
			}
		},
	)

	sqlfuncregistry.QueryRow[func(context.Context, string) (float64, float64, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (float64, float64, error))) = func(ctx context.Context, in0 string) (out0 float64, out1 float64, err error) {
				err = stmt.QueryRowContext(ctx, in0).Scan(&out0, &out1)
				return
			}
		},
	)

	sqlfuncregistry.QueryRow[func(context.Context, string) (string, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (string, error))) = func(ctx context.Context, in0 string) (out0 string, err error) {
				err = stmt.QueryRowContext(ctx, in0).Scan(&out0)
				return
			}
		},
	)

	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 sql.Scanner, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 int, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 interface{Scan(any) error}, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 string, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	sqlfuncregistry.Scan(
		func(rows *sql.Rows, v0 *any) error {
			return rows.Scan(v0)
		},
	)

	sqlfuncregistry.Scan(
		func(rows *sql.Rows, v0 *int) error {
			return rows.Scan(v0)
		},
	)
}
