//go:build sqlfunc_registry_on || !sqlfunc_registry_off

// Code generated by sqlfunc-gen; DO NOT EDIT.

package sqlfunc_test

import "github.com/dolmen-go/sqlfunc/sqlfuncregistry"

import (
	"context"
	sql "database/sql"
	"github.com/dolmen-go/sqlfunc"
)

func init() {
	// stmt_test.go:234
	sqlfuncregistry.Exec[func(context.Context, *sql.Tx, float64, float64, string) (sql.Result, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, *sql.Tx, float64, float64, string) (sql.Result, error))) = func(ctx context.Context, tx *sql.Tx, in0 float64, in1 float64, in2 string) (sql.Result, error) {
				stmtTx := stmt
				if tx != nil {
					stmtTx = tx.StmtContext(ctx, stmt)
					defer stmtTx.Close()
				}
				return stmtTx.ExecContext(ctx, in0, in1, in2)
			}
		},
	)

	// stmt_test.go:58
	// stmt_test.go:135
	sqlfuncregistry.Exec[func(context.Context, float32, float32, string) error](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, float32, float32, string) error)) = func(ctx context.Context, in0 float32, in1 float32, in2 string) (err error) {
				_, err = stmt.ExecContext(ctx, in0, in1, in2)
				return
			}
		},
	)

	// any_test.go:14
	sqlfuncregistry.Exec[func(context.Context, int, int, int) (sql.Result, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, int, int, int) (sql.Result, error))) = func(ctx context.Context, in0 int, in1 int, in2 int) (sql.Result, error) {
				return stmt.ExecContext(ctx, in0, in1, in2)
			}
		},
	)

	// stmt_test.go:808
	sqlfuncregistry.Exec[func(context.Context, string) (sql.Result, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (sql.Result, error))) = func(ctx context.Context, in0 string) (sql.Result, error) {
				return stmt.ExecContext(ctx, in0)
			}
		},
	)

	// scan_test.go:521
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(*int64) error) error {
		var (
			v0 *int64
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		return cb(v0)
	})

	// any_test.go:25
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(bool, string)) error {
		var (
			v0 bool
			v1 string
		)
		if err := rows.Scan(&v0, &v1); err != nil {
			return err
		}
		cb(v0, v1)
		return nil
	})

	// any_test.go:29
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(bool, string, float64)) error {
		var (
			v0 bool
			v1 string
			v2 float64
		)
		if err := rows.Scan(&v0, &v1, &v2); err != nil {
			return err
		}
		cb(v0, v1, v2)
		return nil
	})

	// scan_test.go:155
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(sql.Null[int64]) error) error {
		var (
			v0 sql.Null[int64]
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		return cb(v0)
	})

	// stmt_test.go:360
	// stmt_test.go:395
	// stmt_test.go:434
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(float64, float64)) error {
		var (
			v0 float64
			v1 float64
		)
		if err := rows.Scan(&v0, &v1); err != nil {
			return err
		}
		cb(v0, v1)
		return nil
	})

	// scan_test.go:51
	// scan_test.go:84
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(int)) error {
		var (
			v0 int
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		cb(v0)
		return nil
	})

	// scan_test.go:119
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(int) bool) error {
		var (
			v0 int
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		if !cb(v0) {
			return sqlfunc.Break
		}
		return nil
	})

	// scan_test.go:196
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(int) error) error {
		var (
			v0 int
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		return cb(v0)
	})

	// stmt_test.go:271
	// stmt_test.go:320
	sqlfuncregistry.ForEach(func(rows *sql.Rows, cb func(string)) error {
		var (
			v0 string
		)
		if err := rows.Scan(&v0); err != nil {
			return err
		}
		cb(v0)
		return nil
	})

	// stmt_test.go:220
	// stmt_test.go:310
	// stmt_test.go:706
	sqlfuncregistry.Query[func(context.Context) (*sql.Rows, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context) (*sql.Rows, error))) = func(ctx context.Context) (*sql.Rows, error) {
				return stmt.QueryContext(ctx)
			}
		},
	)

	// stmt_test.go:346
	// stmt_test.go:420
	sqlfuncregistry.Query[func(context.Context, *sql.Tx, string) (*sql.Rows, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, *sql.Tx, string) (*sql.Rows, error))) = func(ctx context.Context, tx *sql.Tx, in0 string) (*sql.Rows, error) {
				stmtTx := stmt
				if tx != nil {
					stmtTx = tx.StmtContext(ctx, stmt)
					defer stmtTx.Close()
				}
				return stmtTx.QueryContext(ctx, in0)
			}
		},
	)

	// any_test.go:22
	sqlfuncregistry.Query[func(context.Context, float64) (*sql.Rows, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, float64) (*sql.Rows, error))) = func(ctx context.Context, in0 float64) (*sql.Rows, error) {
				return stmt.QueryContext(ctx, in0)
			}
		},
	)

	// stmt_test.go:385
	sqlfuncregistry.Query[func(context.Context, string) (*sql.Rows, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (*sql.Rows, error))) = func(ctx context.Context, in0 string) (*sql.Rows, error) {
				return stmt.QueryContext(ctx, in0)
			}
		},
	)

	// stmt_test.go:211
	sqlfuncregistry.QueryRow[func(context.Context) (int64, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context) (int64, error))) = func(ctx context.Context) (out0 int64, err error) {
				err = stmt.QueryRowContext(ctx).Scan(&out0)
				return
			}
		},
	)

	// stmt_test.go:82
	// stmt_test.go:159
	// stmt_test.go:459
	sqlfuncregistry.QueryRow[func(context.Context, string) (float64, float64, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (float64, float64, error))) = func(ctx context.Context, in0 string) (out0 float64, out1 float64, err error) {
				err = stmt.QueryRowContext(ctx, in0).Scan(&out0, &out1)
				return
			}
		},
	)

	// any_test.go:18
	sqlfuncregistry.QueryRow[func(context.Context, string) (int, string, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (int, string, error))) = func(ctx context.Context, in0 string) (out0 int, out1 string, err error) {
				err = stmt.QueryRowContext(ctx, in0).Scan(&out0, &out1)
				return
			}
		},
	)

	// stmt_test.go:762
	sqlfuncregistry.QueryRow[func(context.Context, string) (string, error)](
		func(stmt *sql.Stmt, fnPtr any) {
			*(fnPtr.(*func(context.Context, string) (string, error))) = func(ctx context.Context, in0 string) (out0 string, err error) {
				err = stmt.QueryRowContext(ctx, in0).Scan(&out0)
				return
			}
		},
	)

	// scan_test.go:426
	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 sql.Scanner, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	// scan_test.go:1048
	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 int, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	// scan_test.go:437
	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 interface{Scan(any) error}, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	// scan_test.go:255
	// scan_test.go:320
	sqlfuncregistry.Scan(
		func(rows *sql.Rows) (v0 string, err error) {
			err = rows.Scan(&v0)
			return
		},
	)

	// scan_test.go:362
	sqlfuncregistry.Scan(
		func(rows *sql.Rows, v0 *any) error {
			return rows.Scan(v0)
		},
	)

	// any_test.go:33
	sqlfuncregistry.Scan(
		func(rows *sql.Rows, v0 *bool, v1 *string) error {
			return rows.Scan(v0, v1)
		},
	)

	// any_test.go:38
	sqlfuncregistry.Scan(
		func(rows *sql.Rows, v0 *bool, v1 *string, v2 *float64) error {
			return rows.Scan(v0, v1, v2)
		},
	)

	// scan_test.go:230
	// scan_test.go:295
	// scan_test.go:1027
	sqlfuncregistry.Scan(
		func(rows *sql.Rows, v0 *int) error {
			return rows.Scan(v0)
		},
	)
}
