name: Test and coverage

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.18.x
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check Powershell parsing
        run: |
          TestExe -echoargs go test -v -race -coverprofile coverage.out -covermode atomic ./...
          TestExe -echoargs go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
