name: Test and quality reports

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix: &test-ubuntu-matrix
        go-version:
          - 1.26.x
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps: &test-steps
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test -v -race ./...
      - name: Run tests (sqlfunc_registry_off)
        run: go test -v -race -tags sqlfunc_registry_off ./...
      - name: Run tests (sqlfunc_registry_sync)
        run: go test -v -race -tags sqlfunc_registry_sync ./...


  test-others:
    needs: [ test ]
    strategy:
      matrix:
        go-version:
          - 1.26.x
          - 1.25.x
          - 1.24.x
          # modernc.org/sqlite v1.40+ (used in tests) requires Go 1.24+
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # We used to exclude old versions of Go (up to 1.19) on Windows
        # https://github.com/golang/go/issues/51007
        # exclude:
        #   - os: windows-latest
        #     go-version: 1.19.x
        exclude:
          - *test-ubuntu-matrix
    runs-on: ${{ matrix.os }}
    steps: *test-steps

  quality:
    needs: [ test ]
    strategy:
      matrix: *test-ubuntu-matrix
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout (with full history for SonarQube)
        uses: actions/checkout@v6
        with:
          # Default is 1 (shallow clone with a single commit)
          # but SonarQube wants full history
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download dependencies
        run: go mod download
      - name: Run tests (JSON output, for SonarQube)
        # Powershell Core has problems with '=': -coverprofile=coverage.out
        run: go test -json -coverprofile coverage.1.out -covermode atomic -coverpkg ./... ./... >gotest.out
      - name: Run tests (JSON output, for SonarQube) (sqlfunc_registry_off)
        run: go test -json -coverprofile coverage.2.out -covermode atomic -coverpkg ./... -tags sqlfunc_registry_off ./... >>gotest.out
      - name: Run tests (JSON output, for SonarQube) (sqlfunc_registry_sync)
        run: go test -json -coverprofile coverage.3.out -covermode atomic -coverpkg ./... -tags sqlfunc_registry_sync ./... >>gotest.out
      - name: Merge coverage
        run: |
          cat coverage.?.out >coverage.out
          rm coverage.?.out

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          # https://sonarcloud.io/project/configuration/GitHubActions?id=dolmen-go_sqlfunc
          # https://github.com/dolmen-go/sqlfunc/settings/secrets/actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # See also sonar-project.properties
          args: >
            -Dsonar.go.tests.reportPaths=gotest.out
            -Dsonar.go.coverage.reportPaths=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          # https://github.com/codecov/codecov-action/blob/main/README.md#arguments
          disable_search: true
          files: ./coverage.out
          fail_ci_if_error: true
          report_type: coverage
          disable_telem: true
          # 2026-03: uploading on protected branches without a token doesn't work, even if I'm admin
          # https://app.codecov.io/gh/dolmen-go/sqlfunc/config/general
          # https://github.com/dolmen-go/sqlfunc/settings/secrets/actions/CODECOV_TOKEN
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarQube Quality Gate
        id: sonarqube-quality-gate-check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # FIXME marked as error
      # - name: SonarQube Quality Gate Status
      #   run: echo "SonarQube Quality Gate status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"